services:
  openresty:
    image: openresty:latest
    platform: linux/amd64
    build:
      context: ./openresty
      dockerfile: Dockerfile
    container_name: openresty
    ports:
      - "8080:80"
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    depends_on:
      - frontend
      - backend
  backend:
    image: backend:latest
    container_name: backend
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
  frontend:
    image: frontend:latest
    container_name: frontend
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  frontend_node_modules:
